---
title: "Predict severe irAEs with blood cytometric and proteomic data"
author: "Tiangen Chang <tiangen.chang@nih.gov>"
output:
  rmarkdown::html_vignette:
    toc: true
    toc_depth: 2
vignette: >
  %\VignetteIndexEntry{irAE prediction analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, results = "markup", message = FALSE, warning = FALSE)
```


####### This script makes the below displays for the paper
## Figure 2a-f
## Figure 4a,b
## SFigure 2a-d
## SFigure 6a-g
## STable 6

# Package Loading
```{r}
library(AnnotationDbi)
library(circlize)
library(clusterProfiler)
library(ComplexHeatmap)
library(dplyr)
library(enrichplot)
library(ggplot2)
library(ggpubr)
library(ggrepel)
library(grid)
library(msigdbr)
library(openxlsx)
library(org.Hs.eg.db)
library(pROC)
library(readr)
library(readxl)
library(tidyr)
library(VennDiagram)
```

# Parameters and shared functions
```{r}
result_figure_dir <- "Figures"
data_dir <- "SourceData"

fig_path <- function(...) file.path(result_figure_dir, paste0(...))
data_path <- function(...) file.path(data_dir, paste0(...))

p_to_symbol <- function(p) {
  dplyr::case_when(
    is.na(p) ~ "ns",
    p < 0.001 ~ "***",
    p < 0.01 ~ "**",
    p < 0.05 ~ "*",
    TRUE ~ "ns"
  )
}

convert_gene_ids_to_symbols <- function(gene_ids, mapping) {
  vapply(gene_ids, function(x) {
    entrez_ids <- unlist(strsplit(x, "/"))
    paste(names(mapping)[match(entrez_ids, mapping)], collapse = ", ")
  }, character(1))
}

convert_label_genes <- function(label_genes) {
  label <- vapply(label_genes, function(x) {
    parts <- unlist(strsplit(x, " > "))
    marker <- ifelse(
      grepl("neg$", parts[2]),
      gsub("_", "+", parts[2]),
      paste0(gsub("_", "+", parts[2]), "+")
    )
    paste(marker, gsub("_", "", parts[1]))
  }, character(1))

  replacements <- c(
    TCM = "Tcm", TEMRA = "Temra", TEM = "Tem", NAIVE = "naive",
    TFH = "Tfh", MONO = "Mono", TSCM = "Tscm", TREG = "Treg", BREG = "Breg"
  )

  label <- gsub("^NA\\+\\s*", "", label)
  label <- gsub("neg", "-", label)

  for (old in names(replacements)) {
    label <- gsub(old, replacements[[old]], label)
  }

  label
}

prepare_feature_table <- function(result_df, time_point, modality, map_df) {
  out <- result_df[grepl(time_point, rownames(result_df)), , drop = FALSE]

  if (modality == "flow") {
    out <- out[!grepl("_OLINK_", rownames(out)), , drop = FALSE]
    out$Feature <- sub("_FC.*", "", rownames(out))
    return(out)
  }

  out <- out[grepl("_OLINK_", rownames(out)), , drop = FALSE]
  out$Feature <- sub("_OLINK.*", "", rownames(out))

  map_df <- map_df |>
    dplyr::transmute(
      Feature = as.character(OlinkID),
      GeneSymbol = as.character(Assay)
    )

  out <- merge(out, map_df, by = "Feature", all.x = TRUE, sort = FALSE)
  out$OlinkID <- out$Feature
  out$Feature <- out$GeneSymbol
  out$GeneSymbol <- NULL
  out[!duplicated(out$Feature), , drop = FALSE]
}

plot_venn_three_sets <- function(vec1, vec2, vec3, fig_name) {
  venn_plot <- venn.diagram(
    x = list(AUC = vec1, `Odds ratio` = vec2, `Fold change` = vec3),
    filename = NULL,
    output = TRUE,
    log.filename = NULL,
    imagetype = "pdf",
    compression = "lzw",
    fill = c("#E41A1C", "#377EB8", "#4DAF4A"),
    alpha = 0.5,
    cat.names = NULL,
    cat.cex = 0,
    cat.pos = 0,
    cex = 1.5,
    fontfamily = "sans",
    cat.fontfamily = "sans",
    cat.dist = 0.05
  )

  pdf(fig_name, width = 3.5, height = 3.5)
  grid.draw(venn_plot)
  dev.off()
}

plot_cell_boxplots <- function(
  df,
  cell_pattern,
  cell_display_name,
  ymax = 2,
  ylabel_height = 1.7,
  ytickstep = 0.5,
  labeltextadd = 0.25,
  phenotype = "Severe irAE"
) {
  phenotype_col <- dplyr::case_when(
    phenotype == "Severe irAE" ~ "IRAEactionable01",
    phenotype == "Response" ~ "Response01",
    TRUE ~ NA_character_
  )

  if (is.na(phenotype_col)) {
    stop("phenotype must be either 'Severe irAE' or 'Response'.")
  }

  required_cols <- c(
    paste0(cell_pattern, c("baseline", "ontreat", "FC_on_pre")),
    phenotype_col
  )

  missing_cols <- setdiff(required_cols, colnames(df))
  if (length(missing_cols) > 0) {
    stop("Missing columns: ", paste(missing_cols, collapse = ", "))
  }

  plot_df <- data.frame(
    Pre = df[[paste0(cell_pattern, "baseline")]] / 100,
    On = df[[paste0(cell_pattern, "ontreat")]] / 100,
    FC = df[[paste0(cell_pattern, "FC_on_pre")]],
    Phenotype = factor(df[[phenotype_col]])
  ) |>
    tidyr::pivot_longer(
      cols = c("Pre", "On", "FC"),
      names_to = "Group",
      values_to = "Value"
    ) |>
    tidyr::drop_na() |>
    dplyr::mutate(
      Group = factor(Group, levels = c("Pre", "On", "FC")),
      Combo = interaction(Group, Phenotype, sep = "."),
      Combo = factor(Combo, levels = c("Pre.0", "Pre.1", "On.0", "On.1", "FC.0", "FC.1")),
      x_pos = as.numeric(Combo)
    )

  comparisons <- list(c("Pre.0", "Pre.1"), c("On.0", "On.1"), c("FC.0", "FC.1"))

  pvals <- vapply(comparisons, function(pair) {
    data1 <- plot_df$Value[plot_df$Combo == pair[1]]
    data2 <- plot_df$Value[plot_df$Combo == pair[2]]

    if (length(data1) == 0 || length(data2) == 0) {
      return(NA_real_)
    }

    tryCatch(
      wilcox.test(data1, data2)$p.value,
      error = function(e) NA_real_
    )
  }, numeric(1))

  significance_labels <- p_to_symbol(pvals)
  comparison_pairs <- list(c(1, 2), c(3, 4), c(5, 6))

  p <- ggplot(plot_df, aes(x = x_pos, y = Value, fill = Phenotype, group = Combo)) +
    geom_jitter(width = 0.15, size = 0.5, alpha = 0.7) +
    geom_boxplot(outlier.shape = NA, alpha = 0.6) +
    scale_x_continuous(
      breaks = c(1.5, 3.5, 5.5),
      labels = c("Pre", "On", "FC"),
      expand = expansion(add = 0.4)
    ) +
    scale_y_sqrt(breaks = seq(0, ymax, by = ytickstep)) +
    scale_fill_manual(
      values = c("0" = "#4E79A7", "1" = "#F28E2B"),
      name = phenotype,
      labels = c("No", "Yes")
    ) +
    coord_cartesian(ylim = c(0, ymax)) +
    labs(title = cell_display_name, x = NULL, y = NULL) +
    theme_classic(base_size = 12) +
    theme(
      plot.title = element_text(size = 9, hjust = 0.5),
      axis.text = element_text(color = "black")
    )

  for (i in seq_along(comparison_pairs)) {
    pair <- comparison_pairs[[i]]

    p <- p +
      annotate("segment", x = pair[1], xend = pair[2], y = ylabel_height, yend = ylabel_height, linewidth = 0.5) +
      annotate("segment", x = pair[1], xend = pair[1], y = ylabel_height, yend = ylabel_height - 0.04, linewidth = 0.4) +
      annotate("segment", x = pair[2], xend = pair[2], y = ylabel_height, yend = ylabel_height - 0.04, linewidth = 0.4) +
      annotate("text", x = mean(pair), y = ylabel_height + labeltextadd, label = significance_labels[i])
  }

  p
}

```

# Load data 
```{r}
HCI002_all_info <- read_csv(data_path("HCI002_all_info.csv"), name_repair = "minimal")
HCI002_map_df <- read.csv(data_path("HCI002_OlinkID_ProteinName_map.csv"))

HCI001_all_info <- read_csv(data_path("HCI001_all_info.csv"), name_repair = "minimal")
HCI001_map_df <- read.csv(data_path("HCI001_OlinkID_ProteinName_map.csv"))
```

# SFigure 2a-d. Box plots.
```{r}
phenotype_grouping <- "IRAEactionable01"

cell_population_specs <- list(
  Major = list(
    patterns = c(
      "^CD8_T_", "^CD8_TNAIVE_", "^CD8_TCM_", "^CD4_TEMRA_", "^CD4_TFH_", "^NKT_",
      "^T_CELL_", "^B_CELL_", "^NK_", "^MONO_", "^DC_", "^BASOPHIL_",
      "^GDT_", "^DNT_", "^DPT_", "^CD4_nonTREG_", "^TREG_", "^CD4_nonTFH_",
      "^CD8_TEM_", "^CD8_TEMRA_", "^CD4_TNAIVE_", "^CD4_TCM_", "^CD4_TEM_"
    ),
    labels = c(
      "CD8T cell", "CD8Tnaive cell", "CD8Tcm cell", "CD4Temra cell", "CD4T cell (FH)", "NKT cell",
      "T cell", "B cell", "NK cell", "Monocytes", "DC", "Basophil",
      "GDT cell", "DNT cell", "DPT cell", "CD4T cell (non-Treg)", "Treg cell", "CD4T cell (non-FH)",
      "CD8Tem cell", "CD8Temra cell", "CD4Tnaive cell", "CD4Tcm cell", "CD4Tem cell"
    ),
    ymax = 2, ylabel_height = 1.5, y_step = 0.5, label_offset = 0.25
  ),
  KI67 = list(
    patterns = c(
      "^MONO > KI67_", "^CD8_T > KI67_", "^CD8_TCM > KI67_", "^CD4_nonTFH > KI67_",
      "^TREG > KI67_", "^NKT > KI67_", "^B_CELL > KI67_", "^NK > KI67_",
      "^CD4_TEMRA > KI67_", "^DPT > KI67_", "^DC > KI67_", "^GDT > KI67_",
      "^DNT > KI67_", "^CD4_TFH > KI67_", "^CD8_TNAIVE > KI67_",
      "^CD8_TEM > KI67_", "^CD8_TEMRA > KI67_", "^CD4_TNAIVE > KI67_",
      "^CD4_TCM > KI67_", "^CD4_TEM > KI67_"
    ),
    labels = c(
      "KI67+ Monocytes", "KI67+ CD8T cell", "KI67+ CD8Tcm cell", "KI67+ CD4T cell (non-FH)",
      "KI67+ Treg cell", "KI67+ NKT cell", "KI67+ B cell", "KI67+ NK cell",
      "KI67+ CD4Temra cell", "KI67+ DPT cell", "KI67+ DC", "KI67+ GDT cell",
      "KI67+ DNT cell", "KI67+ CD4T cell (FH)", "KI67+ CD8Tnaive cell",
      "KI67+ CD8Tem cell", "KI67+ CD8Temra cell", "KI67+ CD4Tnaive cell",
      "KI67+ CD4Tcm cell", "KI67+ CD4Tem cell"
    ),
    ymax = 7, ylabel_height = 5.5, y_step = 2, label_offset = 0.875
  ),
  PDL1 = list(
    patterns = c(
      "^MONO > PDL1_", "^CD8_T > PD1_", "^CD4_TEMRA > PD1_", "^CD4_nonTFH > PD1_",
      "^NKT > PD1_", "^DPT > PD1_", "^B_CELL > PDL1_", "^NK > PD1_",
      "^MONO > PD1_", "^DC > PDL1_", "^GDT > PD1_", "^DNT > PD1_",
      "^CD8_T > PDL1_", "^TREG > PD1_", "^TREG > PDL1_", "^CD4_TFH > PD1_",
      "^CD4_TFH > PDL1_", "^CD4_nonTFH > PDL1_", "^CD8_TNAIVE > PD1_",
      "^CD8_TCM > PD1_", "^CD8_TEM > PD1_", "^CD8_TEMRA > PD1_",
      "^CD8_TNAIVE > PDL1_", "^CD8_TCM > PDL1_", "^CD8_TEM > PDL1_",
      "^CD8_TEMRA > PDL1_", "^CD4_TNAIVE > PD1_", "^CD4_TCM > PD1_",
      "^CD4_TEM > PD1_", "^CD4_TNAIVE > PDL1_", "^CD4_TCM > PDL1_",
      "^CD4_TEM > PDL1_", "^CD4_TEMRA > PDL1_"
    ),
    labels = c(
      "PDL1+ Monocytes", "PD1+ CD8T cell", "PD1+ CD4Temra cell", "PD1+ CD4T cell (non-FH)",
      "PD1+ NKT cell", "PD1+ DPT cell", "PDL1+ B cell", "PD1+ NK cell",
      "PD1+ Monocytes", "PDL1+ DC", "PD1+ GDT cell", "PD1+ DNT cell",
      "PDL1+ CD8T cell", "PD1+ Treg cell", "PDL1+ Treg cell", "PD1+ CD4T cell (FH)",
      "PDL1+ CD4T cell (FH)", "PDL1+ CD4T cell (non-FH)", "PD1+ CD8Tnaive cell",
      "PD1+ CD8Tcm cell", "PD1+ CD8Tem cell", "PD1+ CD8Temra cell",
      "PDL1+ CD8Tnaive cell", "PDL1+ CD8Tcm cell", "PDL1+ CD8Tem cell",
      "PDL1+ CD8Temra cell", "PD1+ CD4Tnaive cell", "PD1+ CD4Tcm cell",
      "PD1+ CD4Tem cell", "PDL1+ CD4Tnaive cell", "PDL1+ CD4Tcm cell",
      "PDL1+ CD4Tem cell", "PDL1+ CD4Temra cell"
    ),
    ymax = 2, ylabel_height = 1.5, y_step = 0.5, label_offset = 0.25
  ),
  CTLA4 = list(
    patterns = c(
      "^CD8_T > CTLA4_", "^CD8_TCM > CTLA4_", "^CD4_TEMRA > CTLA4_",
      "^CD4_nonTFH > CTLA4_", "^NKT > CTLA4_", "^DPT > CTLA4_",
      "^MONO > CTLA4_", "^DC > CTLA4_", "^GDT > CTLA4_", "^DNT > CTLA4_",
      "^TREG > CTLA4_", "^CD4_TFH > CTLA4_", "^CD8_TNAIVE > CTLA4_",
      "^CD8_TEM > CTLA4_", "^CD8_TEMRA > CTLA4_", "^CD4_TNAIVE > CTLA4_",
      "^CD4_TCM > CTLA4_", "^CD4_TEM > CTLA4_"
    ),
    labels = c(
      "CTLA4+ CD8T cell", "CTLA4+ CD8Tcm cell", "CTLA4+ CD4Temra cell",
      "CTLA4+ CD4T cell (non-FH)", "CTLA4+ NKT cell", "CTLA4+ DPT cell",
      "CTLA4+ Monocytes", "CTLA4+ DC", "CTLA4+ GDT cell", "CTLA4+ DNT cell",
      "CTLA4+ Treg cell", "CTLA4+ CD4T cell (FH)", "CTLA4+ CD8Tnaive cell",
      "CTLA4+ CD8Tem cell", "CTLA4+ CD8Temra cell", "CTLA4+ CD4Tnaive cell",
      "CTLA4+ CD4Tcm cell", "CTLA4+ CD4Tem cell"
    ),
    ymax = 2, ylabel_height = 1.5, y_step = 0.5, label_offset = 0.25
  )
)

for (population_name in names(cell_population_specs)) {
  spec <- cell_population_specs[[population_name]]

  plot_data <- HCI002_all_info[grepl(paste(spec$patterns, collapse = "|"), colnames(HCI002_all_info))]
  plot_data <- cbind(plot_data, HCI002_all_info[phenotype_grouping])
  plot_data <- plot_data[!grepl("diff|_ABS$", colnames(plot_data))]
  colnames(plot_data) <- gsub("_FC_", "_", colnames(plot_data))
  colnames(plot_data) <- gsub("L3$|L2$", "", colnames(plot_data))

  plot_list <- lapply(seq_along(spec$patterns), function(i) {
    plot_cell_boxplots(
      plot_data,
      cell_pattern = sub("\\^", "", spec$patterns[i]),
      cell_display_name = spec$labels[i],
      ymax = spec$ymax,
      ylabel_height = spec$ylabel_height,
      ytickstep = spec$y_step,
      labeltextadd = spec$label_offset,
      phenotype = "Severe irAE"
    )
  })

  combined_plot <- ggarrange(
    plotlist = plot_list,
    ncol = 6,
    nrow = ceiling(length(plot_list) / 6),
    common.legend = TRUE,
    legend = "bottom"
  )

  ggsave(
    fig_path(population_name, "_boxplots_vs_", phenotype_grouping, "_HCI002.pdf"),
    combined_plot,
    width = 13,
    height = ceiling(length(plot_list) / 6) * 1.95,
    units = "in",
    device = "pdf"
  )
}

```

# Supplementary Table 6. 
```{r} 
phenotype_name <- "IRAEactionable01"
feature_df <- HCI002_all_info[61:25932]
feature_names <- colnames(feature_df)
phenotype <- HCI002_all_info[[phenotype_name]]

calc_feature_stats <- function(values, phenotype) {
  valid_idx <- !is.na(values) & !is.na(phenotype)

  if (sum(valid_idx) < 3 || length(unique(phenotype[valid_idx])) < 2) {
    return(rep(NA_real_, 6))
  }

  values <- values[valid_idx]
  pheno <- phenotype[valid_idx]

  roc_result <- roc(pheno, values, direction = "<", levels = c(0, 1), quiet = TRUE)
  auc_val <- as.numeric(auc(roc_result))

  roc_null <- roc(pheno, rep(0.5, length(pheno)), quiet = TRUE)
  auc_pval <- roc.test(roc_result, roc_null, method = "delong")$p.value

  median_val <- median(values, na.rm = TRUE)
  high_group <- pheno[values > median_val]
  low_group <- pheno[values <= median_val]

  high_ratio <- sum(high_group == 1) / length(high_group)
  low_ratio <- sum(low_group == 1) / length(low_group)
  odds_ratio <- high_ratio / low_ratio

  contingency_tbl <- matrix(
    c(
      sum(high_group == 1), sum(high_group == 0),
      sum(low_group == 1), sum(low_group == 0)
    ),
    nrow = 2,
    byrow = TRUE
  )

  odds_pval <- suppressWarnings(chisq.test(contingency_tbl, correct = FALSE)$p.value)
  fold_change <- median(values[pheno == 1], na.rm = TRUE) / median(values[pheno == 0], na.rm = TRUE)
  wilcox_pval <- wilcox.test(values[pheno == 1], values[pheno == 0])$p.value

  c(auc_val, auc_pval, odds_ratio, odds_pval, fold_change, wilcox_pval)
}

result_columns <- paste0(
  phenotype_name,
  c("_AUC", "_pval1", "_OddsRatio", "_pval2", "_FoldChange", "_pval3")
)

HCI002_result_df <- t(vapply(feature_names, function(feature) {
  calc_feature_stats(feature_df[[feature]], phenotype)
}, numeric(length(result_columns))))

HCI002_result_df <- as.data.frame(HCI002_result_df)
colnames(HCI002_result_df) <- result_columns

HCI002_result_df2 <- HCI002_result_df[!grepl("IGG4|ABS$", rownames(HCI002_result_df)), ]
write.csv(
  HCI002_result_df2,
  file = data_path("HCI002_", phenotype_name, "_AUC_OddsRatio_FoldChange.csv")
)

extract_ranked_results <- function(result_df, pattern, name_pattern) {
  out <- result_df[grepl(pattern, rownames(result_df)), , drop = FALSE]
  rownames(out) <- sub(name_pattern, "", rownames(out))
  out[order(out[[paste0(phenotype_name, "_AUC")]], decreasing = TRUE), , drop = FALSE]
}

df_list <- list(
  CyTOF_pretreatment = extract_ranked_results(HCI002_result_df2, "FC_baseline", "_FC.*$"),
  CyTOF_FoldChange = extract_ranked_results(HCI002_result_df2, "FC_FC", "_FC.*$"),
  CyTOF_ontreatment = extract_ranked_results(HCI002_result_df2, "FC_ontreat", "_FC.*$"),
  OLINK_pretreatment = extract_ranked_results(HCI002_result_df2, "OLINK_baseline", "_OLINK.*$"),
  OLINK_FoldChange = extract_ranked_results(HCI002_result_df2, "OLINK_FC_on_pre", "_OLINK.*$"),
  OLINK_ontreatment = extract_ranked_results(HCI002_result_df2, "OLINK_ontreat", "_OLINK.*$")
)

write.xlsx(df_list, file = data_path("TableS6.xlsx"), rowNames = TRUE)

```

# Figure 2a,c,e/SFigure 6a,c,e. Volcano plots.
```{r}
plot_volcano_panel <- function(result_df, phenotype_name, metric, time_point, modality, map_df, ymax = 10, seed = 1) {
  metric_col <- paste0(phenotype_name, "_", metric)

  df <- result_df[!grepl(">([^F]*_){2,}[^F]*FC", rownames(result_df)), , drop = FALSE]
  df <- prepare_feature_table(df, time_point, modality, map_df)

  df[[paste0(phenotype_name, "_FoldChange")]] <- log2(df[[paste0(phenotype_name, "_FoldChange")]])
  df[[paste0(phenotype_name, "_OddsRatio")]] <- log2(df[[paste0(phenotype_name, "_OddsRatio")]])

  metric_settings <- list(
    AUC = list(p_col = "pval1", x_label = "AUC", lower = 0.4, upper = 0.6, xlim = c(0, 1)),
    OddsRatio = list(p_col = "pval2", x_label = "Log2 (Odds ratio)", lower = -0.25, upper = 0.25, xlim = c(-2, 2)),
    FoldChange = list(p_col = "pval3", x_label = "Log2 (Fold change)", lower = -0.25, upper = 0.25, xlim = c(-2, 2))
  )

  settings <- metric_settings[[metric]]
  if (time_point == "FC_on_pre" && modality == "flow" && metric != "AUC") {
    settings$xlim <- c(-3, 3)
  }

  ylim <- if (phenotype_name == "Response01" || time_point == "baseline") c(0.1, 5) else c(0.1, ymax)
  if (modality == "olink") ylim <- c(0.1, ymax)

  df$FDR <- df[[paste0(phenotype_name, "_", settings$p_col)]]
  de_df <- df |>
    dplyr::transmute(
      Feature_name = Feature,
      EffectorSize = .data[[metric_col]],
      FDR = FDR,
      diffexpressed = dplyr::case_when(
        EffectorSize < settings$lower & FDR < 0.05 ~ "down",
        EffectorSize > settings$upper & FDR < 0.05 ~ "up",
        TRUE ~ "ns"
      )
    )

  label_genes <- union(
    head(de_df$Feature_name[de_df$diffexpressed == "up"][order(de_df$FDR[de_df$diffexpressed == "up"])], 5),
    head(de_df$Feature_name[de_df$diffexpressed == "down"][order(de_df$FDR[de_df$diffexpressed == "down"])], 5)
  )

  label_map <- setNames(convert_label_genes(label_genes), label_genes)
  de_df$delabel <- ifelse(de_df$Feature_name %in% label_genes, label_map[de_df$Feature_name], NA)

  ggplot(de_df, aes(x = EffectorSize, y = -log10(FDR))) +
    geom_vline(xintercept = c(settings$lower, settings$upper), colour = "gray", linetype = "dashed") +
    geom_hline(yintercept = -log10(0.05), colour = "gray", linetype = "dashed") +
    geom_point(aes(colour = diffexpressed), size = 2, alpha = 1, stroke = 0) +
    geom_label_repel(
      aes(label = delabel, colour = diffexpressed),
      size = 3,
      max.overlaps = Inf,
      force = 1,
      force_pull = 1,
      point.padding = 0.25,
      label.padding = 0.25,
      box.padding = 0.25,
      fill = alpha("white", 0.5),
      label.size = NA,
      nudge_y = runif(nrow(de_df), min = -1, max = 1),
      seed = seed,
      show.legend = FALSE
    ) +
    scale_colour_manual(values = c(down = "#00AFBB", ns = "grey", up = "#bb0c00")) +
    scale_y_continuous(breaks = function(x) pretty(x, n = 5)) +
    coord_cartesian(xlim = settings$xlim, ylim = ylim) +
    labs(x = settings$x_label, y = "-Log10 (p)") +
    theme_minimal(base_size = 14) +
    guides(colour = "none") +
    theme(
      panel.grid = element_blank(),
      panel.background = element_rect(fill = "white"),
      axis.line = element_line(color = "black"),
      axis.ticks = element_line(color = "black"),
      axis.text = element_text(color = "black"),
      legend.position = "none"
    )
}

HCI002_result_df <- HCI002_result_df2
phenotype_names_vec <- "IRAEactionable01"
metric_test_suffix_vec <- c("AUC", "OddsRatio", "FoldChange")
timePt_vec <- c("baseline", "ontreat", "FC_on_pre")
data_modality <- "flow"

for (phenotype_name in phenotype_names_vec) {
  for (metric_test_suffix in metric_test_suffix_vec) {
    for (timePt in timePt_vec) {
      p <- plot_volcano_panel(
        HCI002_result_df,
        phenotype_name = phenotype_name,
        metric = metric_test_suffix,
        time_point = timePt,
        modality = data_modality,
        map_df = HCI002_map_df
      )

      pdf(
        fig_path("Volcano_plot_HCI002_", phenotype_name, "_", metric_test_suffix, "_", timePt, "_", data_modality, ".pdf"),
        width = 3.5,
        height = 3.85
      )
      print(p)
      dev.off()
    }
  }
}

```

# Figure 2b,d,f/Figure 4a/SFigure 6b,d,f. Venn plots.
```{r}

phenotype_name <- "IRAEactionable01"
data_modality <- "olink" # olink or flow

thresholds <- list(
  AUC = c(lower = 0.4, upper = 0.6),
  OddsRatio = c(lower = -0.25, upper = 0.25),
  FoldChange = c(lower = -0.25, upper = 0.25)
)

HCI002_result_df <- read.csv(
  data_path("HCI002_", phenotype_name, "_AUC_OddsRatio_FoldChange.csv"),
  row.names = 1
)

HCI002_result_df <- HCI002_result_df[!grepl(">([^F]*_){2,}[^F]*FC", rownames(HCI002_result_df)), ]

get_venn_sets <- function(result_df, time_point, modality, phenotype_name, map_df, thresholds) {
  df <- prepare_feature_table(result_df, time_point, modality, map_df)

  pos <- list(
    AUC = df$Feature[df[[paste0(phenotype_name, "_pval1")]] < 0.05 &
                       df[[paste0(phenotype_name, "_AUC")]] > thresholds$AUC["upper"]],
    OR = df$Feature[df[[paste0(phenotype_name, "_pval2")]] < 0.05 &
                      df[[paste0(phenotype_name, "_OddsRatio")]] > 2^thresholds$OddsRatio["upper"]],
    FC = df$Feature[df[[paste0(phenotype_name, "_pval3")]] < 0.05 &
                      df[[paste0(phenotype_name, "_FoldChange")]] > 2^thresholds$FoldChange["upper"]]
  )

  neg <- list(
    AUC = df$Feature[df[[paste0(phenotype_name, "_pval1")]] < 0.05 &
                       df[[paste0(phenotype_name, "_AUC")]] < thresholds$AUC["lower"]],
    OR = df$Feature[df[[paste0(phenotype_name, "_pval2")]] < 0.05 &
                      df[[paste0(phenotype_name, "_OddsRatio")]] < 2^thresholds$OddsRatio["lower"]],
    FC = df$Feature[df[[paste0(phenotype_name, "_pval3")]] < 0.05 &
                      df[[paste0(phenotype_name, "_FoldChange")]] < 2^thresholds$FoldChange["lower"]]
  )

  list(
    pos = lapply(pos, na.omit),
    neg = lapply(neg, na.omit),
    pos_common = Reduce(intersect, pos),
    neg_common = Reduce(intersect, neg)
  )
}

venn_results <- lapply(
  c(baseline = "baseline", ontreat = "ontreat", FC_on_pre = "FC_on_pre"),
  get_venn_sets,
  result_df = HCI002_result_df,
  modality = data_modality,
  phenotype_name = phenotype_name,
  map_df = HCI002_map_df,
  thresholds = thresholds
)

for (time_point in names(venn_results)) {
  res <- venn_results[[time_point]]

  cat("\nPositive common features -", time_point, "\n")
  cat(convert_label_genes(res$pos_common), sep = "\n")

  cat("\nNegative common features -", time_point, "\n")
  cat(convert_label_genes(res$neg_common), sep = "\n")

  plot_venn_three_sets(
    res$pos$AUC,
    res$pos$OR,
    res$pos$FC,
    fig_name = fig_path(
      "Venn_Features_HCI002_", data_modality, "_", phenotype_name,
      "_Positive_", time_point, ".pdf"
    )
  )

  plot_venn_three_sets(
    res$neg$AUC,
    res$neg$OR,
    res$neg$FC,
    fig_name = fig_path(
      "Venn_Features_HCI002_", data_modality, "_", phenotype_name,
      "_Negative_", time_point, ".pdf"
    )
  )
}

Feature_pos_pre_common <- venn_results$baseline$pos_common
Feature_neg_pre_common <- venn_results$baseline$neg_common
Feature_pos_ontreat_common <- venn_results$ontreat$pos_common
Feature_neg_ontreat_common <- venn_results$ontreat$neg_common
Feature_pos_FC_on_pre_common <- venn_results$FC_on_pre$pos_common
Feature_neg_FC_on_pre_common <- venn_results$FC_on_pre$neg_common

```

# Figure 4b/SFigure 6g. Pathway enrichment plots.
```{r}
get_enrichment_df <- function(enrich_result, id_map, pathway_map = NULL, direction = "Positive") {
  result <- enrich_result@result
  result <- result[result$p.adjust < 0.05, , drop = FALSE]

  if (nrow(result) == 0) {
    return(data.frame())
  }

  pathway <- result$Description
  if (!is.null(pathway_map)) {
    pathway <- pathway_map[pathway]
  }

  data.frame(
    Pathway = pathway,
    AdjPval = result$p.adjust,
    GeneCount = result$Count,
    GeneSymbols = convert_gene_ids_to_symbols(result$geneID, id_map),
    Direction = direction,
    row.names = NULL
  )
}

olink_proteins_pos <- na.omit(Reduce(union, list(
  Feature_pos_FC_on_pre_common,
  Feature_pos_ontreat_common,
  Feature_pos_pre_common
)))

olink_proteins_neg <- na.omit(Reduce(union, list(
  Feature_neg_FC_on_pre_common,
  Feature_neg_ontreat_common,
  Feature_neg_pre_common
)))

olink_proteins_pos_ids <- mapIds(org.Hs.eg.db, keys = olink_proteins_pos, column = "ENTREZID", keytype = "SYMBOL")
olink_proteins_neg_ids <- mapIds(org.Hs.eg.db, keys = olink_proteins_neg, column = "ENTREZID", keytype = "SYMBOL")

msigdb <- msigdbr(species = "Homo sapiens", category = "H")
msigdbr_t2g <- msigdb |>
  dplyr::distinct(gs_name, entrez_gene) |>
  as.data.frame()

MSigDB_mapping <- setNames(
  c(
    "Adipogenesis", "Allograft rejection", "Androgen response", "Angiogenesis",
    "Apical junction", "Apical surface", "Apoptosis", "Bile acid metabolism",
    "Cholesterol homeostasis", "Coagulation", "Complement", "DNA repair",
    "E2F targets", "Epithelial mesenchymal transition", "Estrogen response (early)",
    "Estrogen response (late)", "Fatty acid metabolism", "G2M checkpoint",
    "Glycolysis", "Hedgehog signaling", "Heme metabolism", "Hypoxia",
    "IL2/STAT5 signaling", "IL6/JAK/STAT3 signaling", "Inflammatory response",
    "IFN-alpha response", "IFN-gamma response", "KRAS signaling (down)",
    "KRAS signaling (up)", "Mitotic spindle", "MTORC1 signaling",
    "MYC targets (v1)", "MYC targets (v2)", "Myogenesis", "NOTCH signaling",
    "Oxidative phosphorylation", "P53 pathway", "Pancreas beta cells",
    "Peroxisome", "PI3K/AKT/MTOR signaling", "Protein secretion",
    "Reactive oxygen species pathway", "Spermatogenesis", "TGF-beta signaling",
    "TNFA signaling via NFKB", "Unfolded protein response", "UV response (down)",
    "UV response (up)", "WNT-beta/Catenin signaling", "Xenobiotic metabolism"
  ),
  unique(msigdbr_t2g$gs_name)
)

olink_proteins_pos_MSigDB <- enricher(
  gene = olink_proteins_pos_ids,
  pvalueCutoff = 0.05,
  pAdjustMethod = "BH",
  universe = keys(org.Hs.eg.db),
  minGSSize = 15,
  maxGSSize = 500,
  TERM2GENE = msigdbr_t2g
)

olink_proteins_pos_KEGG <- enrichKEGG(
  gene = olink_proteins_pos_ids,
  organism = "hsa",
  pvalueCutoff = 0.05
)


up_pathways <- olink_proteins_pos_MSigDB
up_pathways@result$Description <- MSigDB_mapping[up_pathways@result$ID]
sig_pathways_NUM <- sum(up_pathways@result$p.adjust < 0.05)
pdf(fig_path("Barplot_MSigDB_pathwayEnrich_HCI002_proteins_irAE.pdf"), width = 3.96, height = 2.4)
barplot(up_pathways, showCategory = sig_pathways_NUM, p.adjust.digits = 1) +
  theme_classic() +
  theme(
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "white"),
    axis.line = element_line(color = "black"),
    axis.text = element_text(color = "black", size = 8),
    axis.text.y = element_text(size = 8, lineheight = 0.8)
  )
dev.off()


up_pathways <- olink_proteins_pos_KEGG 
sig_pathways_NUM <- sum(up_pathways@result$p.adjust < 0.05)
pdf(fig_path("Barplot_KEGG_pathwayEnrich_HCI002_proteins_irAE.pdf"), width = 3.96, height = 2.4)
barplot(up_pathways, showCategory = sig_pathways_NUM, p.adjust.digits = 1) +
  theme_classic() +
  theme(
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "white"),
    axis.line = element_line(color = "black"),
    axis.text = element_text(color = "black", size = 8),
    axis.text.y = element_text(size = 8, lineheight = 0.8)
  )
dev.off()

```

